FROM ubuntu:latest
RUN apt update
RUN apt install python3 python3-pip python3-venv git  -y
WORKDIR /opt/staticjinjaplus
RUN python3 -m venv venv
RUN git clone https://github.com/MrDave/StaticJinjaPlus.git
RUN ./venv/bin/pip3 install -r StaticJinjaPlus/requirements.txt
RUN ./venv/bin/python3 StaticJinjaPlus/main.py --srcpath templates_example/