FROM ubuntu:22.04
RUN apt update && apt install -y \
    python3.11 \
    python3-pip \
    python3-venv \
    git \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /opt/staticjinjaplus
RUN python3 -m venv venv
RUN git clone https://github.com/MrDave/StaticJinjaPlus.git
RUN ./venv/bin/pip3 install -r StaticJinjaPlus/requirements.txt
RUN ./venv/bin/python3 StaticJinjaPlus/main.py --srcpath StaticJinjaPlus/templates_example/