FROM ubuntu:22.04
RUN apt update \
    && apt install -y \
    python3.11 \
    python3-pip \
    python3-venv \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /opt/staticjinjaplus
RUN python3 -m venv venv
ADD https://github.com/MrDave/StaticJinjaPlus.git /opt/staticjinjaplus
RUN ./venv/bin/pip3 install --no-cache-dir -r requirements.txt
RUN ./venv/bin/python3 main.py --srcpath templates_example/
