FROM python:3.11-alpine
WORKDIR /opt/staticjinjaplus
ADD https://github.com/MrDave/StaticJinjaPlus.git /opt/staticjinjaplus
RUN pip3 install --no-cache-dir -r requirements.txt
CMD python main.py --srcpath templates_example/